-- 1. Create the battery_data table
CREATE TABLE IF NOT EXISTS public.battery_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    voltage DOUBLE PRECISION NOT NULL,
    current DOUBLE PRECISION NOT NULL,
    temperature DOUBLE PRECISION NOT NULL,
    soc DOUBLE PRECISION NOT NULL,
    soh DOUBLE PRECISION NOT NULL,
    relay_status BOOLEAN DEFAULT TRUE NOT NULL,
    rul INT DEFAULT 250
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.battery_data ENABLE ROW LEVEL SECURITY;

-- 3. Create a policy to allow anyone to read the data (for demonstration purposes)
CREATE POLICY "Allow public read access" 
ON public.battery_data 
FOR SELECT 
USING (true);

-- 4. Create a policy to allow authenticated inserts (for your backend/ESP32 to push data)
CREATE POLICY "Allow service_role insert" 
ON public.battery_data 
FOR INSERT 
WITH CHECK (true); 

-- 5. Enable Realtime for the table
ALTER PUBLICATION supabase_realtime ADD TABLE public.battery_data;

-- 6. Insert sample data (optional, for testing)
INSERT INTO public.battery_data (voltage, current, temperature, soc, soh, relay_status)
VALUES 
(3.92, 1.25, 38.5, 85.0, 94.0, true),
(3.88, 2.10, 40.2, 82.5, 94.0, true);
